[env:modbus_rtu]
platform = espressif32@6.4.0
board = esp32doit-devkit-v1

; Build flags parameters injection.
build_flags =
  -D BUILD_NAME=\"MODBUS_RTU\"
  -D ENABLE_MOTORS_IO=1
  -D ENABLE_MOTORS=1
  ; -D DEFAULT_MAX_SPEED=1000 ; 100
  ; -D DEFAULT_ACCEL=150 ; 75
  ; -D ENABLE_LIMITS=1
  ; -D ENABLE_ESTOP=1
  ; -D ENABLE_WIFI=1
  ; WiFi settings loaded from .env via pre_build.py
  ; -D ENABLE_MDNS=1
  ; -D ENABLE_NTP=1
  ; -D NTP_TIMEZONE=2
  ; -D ENABLE_WG=1
  ; -D ENABLE_OTA=1
  -D ENABLE_MODBUS=1
  -D MODBUS_RTU=1
  ; -D MODBUS_RTU_BAUDRATE=9600 ; Uses main Serial (UART0)
  ; -D MODBUS_SLAVE_ID=1
  -D ENABLE_INTERPOLATOR=1
  -D ENABLE_WDT=1
  ; -D ENABLE_STATUS_LCD=1

; Local Serial port uploader.
upload_protocol = esptool

; Extend base lib_deps with eModbus
lib_deps =
  ${env.lib_deps}
  https://github.com/eModbus/eModbus
