[env:serial_local]
platform = espressif32@6.4.0
board = esp32doit-devkit-v1

; Build flags parameters injection.
build_flags =
  -D BUILD_NAME=\"SERIAL_LOCAL\"
  -D ENABLE_MOTORS_IO=1
  -D ENABLE_MOTORS=1
  ; -D DEFAULT_MAX_SPEED=1000 ; 100
  ; -D DEFAULT_ACCEL=150 ; 75  -D PRC_MIN=-100
  ; -D ENABLE_LIMITS=1
  ; -D ENABLE_ESTOP=1
  -D ENABLE_WIFI=1
  ; WiFi settings loaded from .env via pre_build.py
  -D ENABLE_MDNS=1
  -D ENABLE_NTP=1
  ; -D NTP_TIMEZONE=2
  ; -D NTP_1=\"ntp.jst.mfeed.ad.jp\"
  ; -D NTP_2=\"ntp.nict.jp\"
  ; -D NTP_3=\"time.google.com\"
  ; -D ENABLE_WG=1
  ; WireGuard settings loaded from .env via pre_build.py
  -D ENABLE_OTA=1
  ; OTA settings loaded from .env via pre_build.py
  ; Calculate the password hash: https://www.md5hashgenerator.com/
  -D ENABLE_SUPER=1
  ; -D SUPER_SERVICE_PORT=10182
  -D ENABLE_INTERPOLATOR=1
  -D ENABLE_WDT=1
  -D ENABLE_STATUS_LCD=1

; Local Serial port uploader.
upload_protocol = esptool
