#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
@file pre_build.py
@brief PlatformIO pre-build script for loading environment variables.

This script is executed before the build process and loads environment
variables from a .env file in the project root directory. The variables
are then merged into the build environment, making them available to
the PlatformIO build system.

@note Created with the help of Ivanushka (ChatGPT)
"""

import os
import re

Import("env")

_NUMERIC_RE = re.compile(r"^-?\d+(\.\d+)?$")


def _load_env_file(path):
    envs = {}
    if not os.path.exists(path):
        return envs
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or line.startswith(";"):
                continue
            if "=" not in line:
                continue
            key, value = line.split("=", 1)
            envs[key.strip()] = value.strip().strip('"').strip("'")
    return envs


def _coerce_value(raw_value):
    if _NUMERIC_RE.match(raw_value):
        try:
            return int(raw_value)
        except ValueError:
            return float(raw_value)
    escaped = raw_value.replace("\\", "\\\\").replace("\"", "\\\"")
    return f"\"{escaped}\""


def _inject_defines(env_map):
    defines = []
    for key in _DEFINE_KEYS:
        value = env_map.get(key)
        if value is None:
            continue
        defines.append((key, _coerce_value(value)))
    if defines:
        env.AppendUnique(CPPDEFINES=defines)


def _maybe_print_env(env_map):
    env_name = env.get("PIOENV", "")
    if env_name != "env_dump":
        return
    print("==== .env values (resolved) ====")
    for key in _DEFINE_KEYS:
        if key in env_map:
            print(f"{key}={env_map[key]}")
    print("================================")

    build_flags = env.get("BUILD_FLAGS", [])
    if build_flags:
        print("==== build flags (resolved) ====")
        for flag in build_flags:
            print(flag)
        print("================================")

    cpp_defines = env.get("CPPDEFINES", [])
    if cpp_defines:
        print("==== cpp defines (resolved) ====")
        print(cpp_defines)
        print("================================")


def _write_env_header(env_map, project_dir):
    header_path = os.path.join(project_dir, "lib", "EnvDump", "EnvDumpConfig.h")
    lines = [
        "#ifndef ENVDUMP_CONFIG_H",
        "#define ENVDUMP_CONFIG_H",
        "",
        "// Auto-generated by pre_build.py. Do not commit secrets.",
        "",
    ]
    for key in _DEFINE_KEYS:
        value = env_map.get(key)
        if value is None:
            continue
        if _NUMERIC_RE.match(value):
            define_value = value
        else:
            escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
            define_value = f"\"{escaped}\""
        lines.append(f"#define {key} {define_value}")
    lines.append("")
    lines.append("#endif // ENVDUMP_CONFIG_H")
    content = "\n".join(lines) + "\n"
    with open(header_path, "w") as f:
        f.write(content)


_DEFINE_KEYS = [
    "WIFI_SSID",
    "WIFI_PASS",
    "OTA_PORT",
    "OTA_HOST_NAME",
    "OTA_PASS_HASH",
    "WG_ENDPOINT",
    "WG_LOCAL_IP",
    "WG_PRIVATE_KEY",
    "WG_PUBLIC_KEY",
    "PS4_MAC",
]

# Load variables from .env file in project root. External environment values
# take precedence when provided.
project_dir = env.get("PROJECT_DIR", os.getcwd())
dotenv_path = os.path.join(project_dir, ".env")
file_vars = _load_env_file(dotenv_path)
merged = dict(file_vars)
merged.update({k: v for k, v in os.environ.items() if k in _DEFINE_KEYS})

_inject_defines(merged)
_maybe_print_env(merged)
_write_env_header(merged, project_dir)
